---
services:
  mitten:
    build: .
    container_name: mitten
    environment:
      - TZ=America/New_York
    env_file:
      - .env
    volumes:
      - ./commit_log.json:/app/commit_log.json
    restart: unless-stopped
